### ISSUE TITLE
LGChatController doesn't show UINavigationBar

### ISSUE THREAD

**Issue by Byteros** [LoganWright/SimpleChat#22]
Hi Logan,

I have a little problem.
I have this storyboard configuration:
tabBarController -> navigationController -> myListMessageView -> LGChatView

When i make PUSH, uinavigationBar of LGChat is not shown.
I use with this code:

    LGChatController *chatController = [LGChatController new];
    chatController.opponentImage = [UIImage imageNamed:imageName];
    chatController.title = titleView;
    
    //Inizializza con un messaggio
    LGChatMessage *helloWorld = [[LGChatMessage alloc] initWithContent:@"Ciao sporcacciona" sentByString:[LGChatMessage SentByUserString]];
    
    chatController.messages = @[helloWorld]; // Pass your messages here.
    chatController.delegate = self;

    //Hide tabbarcontroller, else tabBar hides the textField
    self.tabBarController.tabBar.hidden = YES;
    
    [self.navigationController pushViewController:chatController animated:YES];

I would use the same navigationBar of myListMessageView.
I hope you can help me.

Thank you. ;)

See the images:

![ios simulator screen shot 27 feb 2015 20 08 06](https://cloud.githubusercontent.com/assets/1682892/6419315/60b4901c-bebc-11e4-9f6d-67ae64e27a60.png)
![ios simulator screen shot 27 feb 2015 20 08 08](https://cloud.githubusercontent.com/assets/1682892/6419316/60e03154-bebc-11e4-9a7f-863f3682f519.png)

**Comment by LoganWright** [comment]
Hi @Byteros 

I'm not sure exactly what would be causing the navigation bar to disappear in this situation, would you be able to show me the project it's in and perhaps I'd be able to find out what specifically is causing the navigation bar to hide?

For now, just for sanity sake, can you try setting the navigation bar not hidden explicitly by calling,

```ObjC
self.navigationController.navigationBarHidden = NO; 
```

After pushing the chat controller.  

I suspect this has something to do w/ the navigation bar, tab bar combination, it's just really hard to diagnose from the outside.

Best

Logan

**Comment by Byteros** [comment]
SOLVED.

But when i return to myListMessageView the navigationBar is like the LGChatView navigation bar.
I have solved this problem also with this line in viewwillAppear:

    [self.navigationController setNavigationBarHidden:YES];

I don't like this solution but works fine.

**Comment by PrincessMine** [comment]
Hi LoganWright,
I want to add thumbnail of Images in tableViewCell to share media files in LGSimpleChat, Same like WhatsApp is working.

Thanks in advance
