### ISSUE TITLE
Adding support to show msg timestamp

### ISSUE THREAD

**Issue by strazin** [LoganWright/SimpleChat#23]
Hi Logan,

Awesome library!  I am looking for a recommendation on how to easily add a msg timestamp in between chat bubbles.  Can you recommend the best way to add this?

Thanks

**Comment by LoganWright** [comment]
Hi @strazin 

Sorry for the late reply,  I don't have a quick solution off hand, but perhaps its as simple as doubling the count of cells and injecting a time stamp cell for each index that is even, ie: 0, 2, 4, 6, etc.

Let me know if you build that, and definitely submit a PR!

Best, and good luck.

**Comment by danyball** [comment]
@strazin Could you post your solution? Want to show the timestamp, too.

@LoganWright Nice and easy library!

**Comment by LoganWright** [comment]
Closing this for now, if someone wants to implement this, please submit a pull request!
