### ISSUE TITLE
Multiple Opponents

### ISSUE THREAD

**Issue by crhuber** [LoganWright/SimpleChat#26]
Hello,
is it possible to have multiple opponents each with a different avatar? 
I would like to try to use this when having a group chat with multiple people. Is there a way I can implement that?

**Comment by LoganWright** [comment]
HI @crhuber 

As of now, this library only supports single opponents.  This may change in the future, but the library isn't actively adding new features, so it's more likely to be added if someone adds it!

If you're feeling adventurous and want to add this feature to the current implementation, definitely submit a pull request for it!

In the meantime, you need a chat gui for your app that handles groups, so if you don't have the time to add the feature to this library, perhaps something like <a href="https://github.com/layerhq/Atlas-iOS">Atlas</a> would be a good alternative.

Best,

Logan
