### ISSUE TITLE
ObjC not finding swift

### ISSUE THREAD

**Issue by bendparker** [LoganWright/SimpleChat#27]
I love this idea, and I believe I've followed the instructions correctly, however, I cannot seem to get my project to see the LGChatController...I've checked the settings in the properties.  Please see below.  Any help is appreciated.

![screen shot 2015-05-16 at 11 32 27 am](https://cloud.githubusercontent.com/assets/10870861/7666797/559e58ee-fbbf-11e4-83a6-fb6c9d913688.png)

**Comment by LoganWright** [comment]
Hi @bendparker 

Sorry for the late reply, were you able to figure this out?

I've heard that to use Swift in ObjC within your project, sometimes you need to add the bridging header for ObjC to Swift.  Even if you don't use it, it seems to help in the generation of the Swift header.

If that doesn't work, perhaps you could push your project and I could take a look?

Best,

Logan

**Comment by bendparker** [comment]
I have not gotten it. I moved on to another project but will be circlin back to this shortly. 

I'll had he header and see what happens 

Thanks,
Ben
