### ISSUE TITLE
Multiple line message causes app to crash when running iOS 9

### ISSUE THREAD

**Issue by saiftase** [LoganWright/SimpleChat#31]
When text fills up the first line of the input field field, the app crashes, rather than having the text continue on to the next line. This issue only occurs after updating to iOS 9.

https://streamable.com/iqdl

Let's see if I can get this running on Xcode and find some relevant information in the logs.

**Comment by Byteros** [comment]
YES, I have The same problem.

**Comment by LoganWright** [comment]
Hey guys, 

I submitted a patch to the library a little while ago, soon after Xcode 7 GM came out. Can you confirm you're still having problems on the latest version?

- Logan

**Comment by saiftase** [comment]
Yeah, just saw the update, and everything is working fine now.
