### ISSUE TITLE
Chat bubble not expanding vertically if i type a lot

### ISSUE THREAD

**Issue by bt1** [LoganWright/SimpleChat#32]
When I input about 10 lines of text into the text bubble, they start to break and cover over the messages after that.

**Comment by LoganWright** [comment]
Hi @bt1,

I'm unable to reproduce this error, 10+ lines is running fine for me.  Can you verify that you're on the latest version, and perhaps provide steps necessary to recreate the error?

Best,

Logan

**Comment by LoganWright** [comment]
closing as cannot reproduce.
