### ISSUE TITLE
Unclear instruction for usage from Swift

### ISSUE THREAD

**Issue by geophile** [LoganWright/SimpleChat#37]
I am a new iOS developer, so it is entirely possible this is just unclear to me. 

The first instruction under Swift says: Import <#YourProductModule#>-Swift.h

What does this mean? Where does the import go? And what is <#YourProductModule#>-Swift.h? I don't believe my code has one of these. Or should it be something like SimpleChat-Swift.h?

By the way, this looks like useful code, and I'm learning quite a bit just reading it.

**Comment by LoganWright** [comment]
Hi @geophile 

If you're working in Swift, none of this applies. It's only relevant to those wishing to import this library into their ObjC code base. To do that, you have to use your product module which is usually created for you.

Are you writing in Swift or ObjC?

**Comment by geophile** [comment]
Thanks for your reply. I’m working in Swift, and SimpleChat is working fine.
