### ISSUE TITLE
Are timestamps ignored?

### ISSUE THREAD

**Issue by Cero9** [LoganWright/SimpleChat#38]
Hello, I'm using SimpleChat in my current project.
I used timestamps to save the order of messages (I don't need the exact date to be displayed) to CoreData, but when I load, timestamp simply gets ignored.
My question is then, what is timestamp for? Timestamps doesn't get updated when a message is sent/received, and it's also ignored why the message is added back.
Am I using that the wrong way? Any hint?

**Comment by LoganWright** [comment]
Hi @Cero9 

Right now, timestamps are more of a placeholder that was intended to be used for future behavior that includes them with the messages.

At the moment, it's not being used for anything.

Are you asking for a certain order? If so, SimpleChat loads in the order it receives messages. If you want to have a specific order you'll need to sort beforehand.

Let me know if you have more specifics and if there's a bug, we can get it patched.

Best,

Logan

**Comment by Cero9** [comment]
Ok I understand, I assumed it was used :smile: 
I accomplished my goal by manually setting the timestamp where the message is created, and then ordering them by the timestamps when they are loaded by the CoreData, so that they are added in the right order.

No bug I guess, then.
Great work BTW!
