### ISSUE TITLE
Error on OBJ C

### ISSUE THREAD

**Issue by rulazzZ** [LoganWright/SimpleChat#39]
I'm trying to add the chat interface to my OBJ C project but i got and error at this line:
LGChatController *chatController = [LGChatController new];

and with Delgated methods too.

Whats wrong?

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$__TtC10SimpleChat13LGChatMessage", referenced from:
      objc-class-ref in ContactoWithLoginViewController.o
  "_OBJC_CLASS_$__TtC10SimpleChat16LGChatController", referenced from:
      objc-class-ref in ContactoWithLoginViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by LoganWright** [comment]
@rulazzZ I haven't checked w/ ObjC in a while, I'm not really sure what's happening here. Do you have any other info that might help us figure out what's going on?

**Comment by rulazzZ** [comment]
I resolve that going to Project - Build Settings and Changing my Product Module Name to SimpleChat, thank you anyways :)

**Comment by LoganWright** [comment]
@rulazzz good luck with the rest of your project
